name: Daily Gemini Telegram Bot

on:
  schedule:
    # Runs every day at 5:00 AM Indonesia time (UTC+7) = 22:00 UTC (previous day)
    - cron: '0 22 * * *'
      timezone: 'Asia/Jakarta'
  
  # Allows manual triggering for testing
  workflow_dispatch:

jobs:
  send-gemini-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip packages
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Verify imports
      run: |
        python -c "import google.genai as genai; from google.genai import types; print('✅ All imports successful!')"
    
    - name: Run Telegram Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python telegram_gemini_bot.py